// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ride2Gedda.Migrations
{
    [DbContext(typeof(Ride2GeddaDBContext))]
    [Migration("20260305044325_RecreateDatabase")]
    partial class RecreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ride2Gedda.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ride2Gedda.Models.BusRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusRouteNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusRouteType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Depot")
                        .HasColumnType("text");

                    b.Property<int>("DestinationId")
                        .HasColumnType("integer");

                    b.Property<int>("OriginId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.ToTable("BusRoutes");
                });

            modelBuilder.Entity("Ride2Gedda.Models.BusRouteSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusRouteId")
                        .HasColumnType("integer");

                    b.Property<int?>("DayType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusRouteId");

                    b.ToTable("BusRouteSchedules");
                });

            modelBuilder.Entity("Ride2Gedda.Models.BusRouteViaStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusRouteId")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<int>("StopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StopId");

                    b.HasIndex("BusRouteId", "Sequence")
                        .IsUnique();

                    b.ToTable("BusRouteViaStops");
                });

            modelBuilder.Entity("Ride2Gedda.Models.FavouriteBusRoute", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("BusRouteId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "BusRouteId");

                    b.HasIndex("BusRouteId");

                    b.ToTable("FavouriteBusRoutes");
                });

            modelBuilder.Entity("Ride2Gedda.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BusRouteId")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusRouteId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Ride2Gedda.Models.RefreshToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Ride2Gedda.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BusRouteId")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Upvotes")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusRouteId");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Ride2Gedda.Models.ScheduleStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("ArrivalTime")
                        .HasColumnType("interval");

                    b.Property<int>("BusRouteScheduleId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("DepartureTime")
                        .HasColumnType("interval");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<int>("StopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StopId");

                    b.HasIndex("BusRouteScheduleId", "Sequence")
                        .IsUnique();

                    b.ToTable("ScheduleStops");
                });

            modelBuilder.Entity("Ride2Gedda.Models.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("Ride2Gedda.Models.BusRoute", b =>
                {
                    b.HasOne("Ride2Gedda.Models.Stop", "Destination")
                        .WithMany("DestinationBusRoutes")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ride2Gedda.Models.Stop", "Origin")
                        .WithMany("OriginBusRoutes")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("Ride2Gedda.Models.BusRouteSchedule", b =>
                {
                    b.HasOne("Ride2Gedda.Models.BusRoute", "BusRoute")
                        .WithMany("Schedules")
                        .HasForeignKey("BusRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusRoute");
                });

            modelBuilder.Entity("Ride2Gedda.Models.BusRouteViaStop", b =>
                {
                    b.HasOne("Ride2Gedda.Models.BusRoute", "BusRoute")
                        .WithMany("ViaStops")
                        .HasForeignKey("BusRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ride2Gedda.Models.Stop", "Stop")
                        .WithMany("ViaBusRoutes")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusRoute");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("Ride2Gedda.Models.FavouriteBusRoute", b =>
                {
                    b.HasOne("Ride2Gedda.Models.BusRoute", "BusRoute")
                        .WithMany("FavouriteByUsers")
                        .HasForeignKey("BusRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ride2Gedda.Models.ApplicationUser", "User")
                        .WithMany("FavouriteBusRoutes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusRoute");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ride2Gedda.Models.Notification", b =>
                {
                    b.HasOne("Ride2Gedda.Models.BusRoute", "BusRoute")
                        .WithMany()
                        .HasForeignKey("BusRouteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ride2Gedda.Models.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusRoute");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ride2Gedda.Models.RefreshToken", b =>
                {
                    b.HasOne("Ride2Gedda.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ride2Gedda.Models.Report", b =>
                {
                    b.HasOne("Ride2Gedda.Models.BusRoute", "BusRoute")
                        .WithMany()
                        .HasForeignKey("BusRouteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ride2Gedda.Models.ApplicationUser", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusRoute");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ride2Gedda.Models.ScheduleStop", b =>
                {
                    b.HasOne("Ride2Gedda.Models.BusRouteSchedule", "BusRouteSchedule")
                        .WithMany("Stops")
                        .HasForeignKey("BusRouteScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ride2Gedda.Models.Stop", "Stop")
                        .WithMany("ScheduleStops")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusRouteSchedule");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("Ride2Gedda.Models.ApplicationUser", b =>
                {
                    b.Navigation("FavouriteBusRoutes");

                    b.Navigation("Notifications");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Ride2Gedda.Models.BusRoute", b =>
                {
                    b.Navigation("FavouriteByUsers");

                    b.Navigation("Schedules");

                    b.Navigation("ViaStops");
                });

            modelBuilder.Entity("Ride2Gedda.Models.BusRouteSchedule", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("Ride2Gedda.Models.Stop", b =>
                {
                    b.Navigation("DestinationBusRoutes");

                    b.Navigation("OriginBusRoutes");

                    b.Navigation("ScheduleStops");

                    b.Navigation("ViaBusRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
